version: '3' 
services:
    app:
        build: .    
        image: covid19spainapi:latest
        network_mode: bridge
        ports:
            - "8081:8181"          
        volumes:
            - sqlite-db:/data
volumes:
        sqlite-db:
        