version: '3' 
services:
    app:
        build: .    
        image: covid19spainapi:latest
        ports:
            - "8081"          
        volumes:
            - sqlite-db:/data
    lb:
        image: dockercloud/haproxy
        ports:
            - 80:80
        links:
            - app
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
volumes:
        sqlite-db: 