INSERT INTO comunidad_autonoma (ccaa, nombre)
VALUES
("AN","Andalucía"),	
("AR", "Aragón"),		
("AS", "Asturias"),	
("IB", "Baleares"),	
("CN", "Canarias"),	
("CB", "Cantabria"),	
("CM", "Castilla-La Mancha"),	
("CL", "Castilla y León"),		
("CT", "Cataluña"),	
("CE", "Ceuta"),	
("VC", "C. Valenciana"),	
("EX", "Extremadura"),	
("GA", "Galicia"),	
("MD", "Madrid"),	
("ML", "Melilla"),	
("MC", "Murcia"),	
("NC", "Navarra"),	
("PV", "País Vasco"),
("RI", "La Rioja");