create table ComunidadAutonoma (id smallint not null, nombre varchar, primary key (id))
create table hibernate_sequence (next_val bigint)
insert into hibernate_sequence values ( 1 )
insert into hibernate_sequence values ( 1 )
create table Provincia (id smallint not null, nombre varchar, comunidadAutonoma smallint, primary key (id))
create table ComunidadAutonoma (id smallint not null, nombre varchar, primary key (id))
create table hibernate_sequence (next_val bigint)
insert into hibernate_sequence values ( 1 )
insert into hibernate_sequence values ( 1 )
create table Provincia (id smallint not null, nombre varchar, comunidadAutonoma smallint, primary key (id))
create table ComunidadAutonoma (id smallint not null, nombre varchar, primary key (id))
create table hibernate_sequence (next_val bigint)
insert into hibernate_sequence values ( 1 )
insert into hibernate_sequence values ( 1 )
create table Provincia (id smallint not null, nombre varchar, comunidadAutonoma smallint, primary key (id))
create table ComunidadAutonoma (id smallint not null, nombre varchar, primary key (id))
create table hibernate_sequence (next_val bigint)
insert into hibernate_sequence values ( 1 )
insert into hibernate_sequence values ( 1 )
create table Provincia (id smallint not null, nombre varchar, comunidadAutonoma smallint, primary key (id))
create table ComunidadAutonoma (id smallint not null, nombre varchar, primary key (id))
create table hibernate_sequence (next_val bigint)
insert into hibernate_sequence values ( 1 )
insert into hibernate_sequence values ( 1 )
create table Provincia (id smallint not null, nombre varchar, comunidadAutonoma smallint, primary key (id))
